proc import datafile="C:/Users/dcries/github/ra_dot/data/completedata_nona.csv" out=dot dbms=csv replace;
    getnames=yes;
run;

data dot;
	set dot;
	logMILES = log(MILES);
	run;

proc HPGenselect data=dot;
	class ACCESSCNTL COMNETWORK CORPCITY CURBEDL CURBEDR DIRECTION
   FEDFUNC JURISDIC MEDTYPE RUMBLEL RUMBLER SURFTYPE SYSCODE TERRAIN TRANSCENTE TRUCKRTE NATHWYSYS SHDTIEDL
  SHDTIEDR SHDTYPEL SHDTYPER URBANAREA ;
  model CRASHES = VOLUME BUS CRACKPATCH NUMLANES LIMITMPH AADT IRI MEDWIDTH PICKUP PSIRATING SINGLEUNIT
  SINGMULTTR SURFWIDTH SHDWIDTHL SHDWIDTHR
	ACCESSCNTL COMNETWORK CORPCITY CURBEDL CURBEDR DIRECTION
   FEDFUNC JURISDIC MEDTYPE RUMBLEL RUMBLER SURFTYPE SYSCODE TERRAIN TRANSCENTE TRUCKRTE NATHWYSYS SHDTIEDL
  SHDTIEDR SHDTYPEL SHDTYPER URBANAREA / dist=Poisson link = Log offset = logMILES;
  performance details;
  selection method=stepwise(choose=aicc);
  run;
  
  proc glm data=dot;
class ACCESSCNTL COMNETWORK CORPCITY;
model CRASHES = ACCESSCNTL COMNETWORK CORPCITY;
means ACCESSCNTL /alpha=0.05 bon lsd tukey;
run;
